=== nadiaskau/JSON-Schema/opgave2.schema.json
{
	"$id": "https://example.com/iba-pbw.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "IBA",
	"description": "Information about IBA Ervhervsakademi Kolding",
	"type": "object",
	"properties": {
		"vat" : {"type" : "number"}, 
		"name" : {"type" : "string"},
		"address" : {"type" : "string"},
		"zipcode" : {"type" : "number"},
		"city" : {"type" : "string"}, 
		"phone" : {"type" : "number"},
		"email" : {"type" : "string"}, 
		"employees" : {"type" : "string"},
		"industrydesc" : {"type" : "string"},
		"companydesc" : {"type" : "string"},
		"creditbankrupt": {"type" : "boolean"},
		"productionunits": {"type": "array"},
			"items" : {"type" : "object"}, 
				"properties" : {
					"pno": {"type" : "number"},
					"name": {"type" : "string"},
					"address": {"type" : "string"},
					"zipcode": {"type" : "number"},
					"city": {"type" : "string"},
					"phone": {"type" : "number"}
				},
				"properties" : {
					"email": {"type" : "string"},
					"startdate": {"type" : "string"},
					"enddate": {"type" : "string"},
					"employees": {"type" : "null"},
					"industrydesc": {"type" : "string"}
				},
		"version" : {"type" : "number"}
	}
}

=== nadiaskau/JSON-Schema/opgave2.json
{
    "vat": 31642124,
    "name": "IBA Erhvervsakademi Kolding S/I",
    "address": "Havneparken 1",
    "zipcode": 6000,
    "city": "Kolding",
    "phone": 72118200,
    "email": "iba@iba.dk",
    "employees": "200-499",
    "industrydesc": "Videregående uddannelser ikke på universitetsniveau",
    "companydesc": "Øvrige virksomhedsformer",
    "creditbankrupt": false,
    "productionunits": [
       {
          "pno": 1021574526,
          "name": "Erhvervsakademi Kolding",
          "address": "Nytorv 2",
          "zipcode": 6000,
          "city": "Kolding",
          "phone": 72118200
       },
       {
          "email": "iba@iba.dk",
          "startdate": "01/11 - 2014",
          "enddate": "18/08 - 2019",
          "employees": null,
          "industrydesc": "Videregående uddannelser ikke på universitetsniveau"
       }
    ],
    "version": 6
 }
